### ISSUE TITLE
Experiment Data Pipe doesn't return soma_joinids

### ISSUE THREAD

**Issue by yanwu2014** [chanzuckerberg/cellxgene-census#1289]
The `ExperimentDataPipe` no longer returns `soma_joinids` by default if nothing is specified in the `obs_column_names` parameter

Specifically:
```
datapipe = ml.pytorch.ExperimentDataPipe(
            experiment=my_soma_experiment,
            measurement_name='RNA',
            obs_query=obs_query,
            obs_column_names=[], ## No obs columns specified
)
tensor, soma_ids = next(iter(datapipe))
```
I expected `soma_ids` to be a tensor of obs indexes but instead it's an empty tensor. It seems like it's due to a potential bug in the `_ObsAndXIterator` class on [line 340 in pytorch.py](https://github.com/chanzuckerberg/cellxgene-census/blob/af68b5e29da46e1b83bd3c09fd6c5d046772fa74/api/python/cellxgene_census/src/cellxgene_census/experimental/ml/pytorch.py#L340) where:
`obs["soma_joinid"] = obs.index` should instead be
`obs_encoded["soma_joinid"] = obs.index` since `obs_encoded` is what gets turned into `obs_tensor` and returned

Happy to put together a PR if this seems like the issue

**Comment by ivirshup** [comment]
Thanks for the bug report @yanwu2014!

This change was actually intentional. We figured that it would be easier to work with the loader if there was less implicit behavior, especially when that implicit behavior ends up complicating the offsets you need to access the encoded variables. Now if you want the soma join ids you can access them by explicitly requesting them.

**Comment by yanwu2014** [comment]
Ah I see, thanks for clarifying! Just a heads up I think the docstrings still say that the soma join ids will always be returned but I'll close this issue for now
