### ISSUE TITLE
Provide field descriptors study-level metadata outside of cellxgene schema

### ISSUE THREAD

**Issue by emdann** [chanzuckerberg/cellxgene-census#1321]
## Description

It's great to have access to study-specific data (outside of the cxg schema) from census with `download_source_h5ad`. I find myself needing to access this data for most of the datasets that I find and download with CxG census/collections. 

This might be a big ask, but it would be extremely useful to require (or suggest adding) a free-text field description for each non-standard column in adata.obs submitted to the CxG database. Often the column names are not self-explanatory, and the column names are not documented in the original sources linked in the collection pages. 

## Context

I was trying to extract condition-specific clinical metadata from several human disease datasets (e.g. [this one](https://cellxgene.cziscience.com/collections/e1a9ca56-f2ee-435d-980a-4f49ab7a952b)) 

## Alternatives you've considered

I've browsed through supplementary materials of papers, code repos and e-mailed corresponding authors

## Ideal behavior

Source .h5ad files could contain an `adata.uns['obs_field_description']` with a dictionary of `{'obs_key':"Description", ... }`. Or even better, with census-based access to study-specific metadata (https://github.com/chanzuckerberg/cellxgene-census/issues/363), descriptions could be included there?

**Comment by brianraymor** [comment]
Hi @emdann,

@ivirshup brought your suggestion to my attention. 

CELLxGENE needs to balance value to submitters and consumers. As a result, we've steered clear of "recommended" free text fields because it adds burden to the submitter without guaranteeing consumer value. The [dataset schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md) generally requires ontology terms or controlled vocabularies to deliver a consistent, high-quality experience.

Also note, that there are datasets where submitters have included MANY (100+) author submitted fields. 

If a field description was required (MUST), then:
- Submitters might include less or no author submitted fields in datasets.
- The _not self-explanatory column name_ might be copied to the free text value of the field description. (I've seen similar patterns in the past.)

**Comment by emdann** [comment]
Thanks for the detailed reply @brianraymor. Totally understand the logic, and it's probably wishful thinking that submitters would fill it out as a "recommended" field. 

Feel free to close. Other features to increase the usability of author submitted metadata would be very useful IMO (big up for #363).

**Comment by brianraymor** [comment]
> Other features to increase the usability of author submitted metadata would be very useful IMO (big up for https://github.com/chanzuckerberg/cellxgene-census/issues/363).

Is [`observation_joinid`](https://github.com/chanzuckerberg/cellxgene-census/issues/363#issuecomment-2310763238) inadequate for your needs?

**Comment by emdann** [comment]
I often use census to analyse tables of cell- and sample-level metadata before downloading h5ads, to decide whether I want to include or exclude a dataset or subset of cells from analysis. Often info in the author metadata informs that decision, but right now I can only access it by downloading the whole h5ad for a dataset. It would be great to be able to browse the column names of the author metadata for a certain `dataset_id`, or even better to download the full `adata.obs` for a dataset_id without downloading all the count matrices.

I don't have access to the colab notebook in the referenced issue, so I am not sure whether this shows how to do exactly that. If so, I would add it to the docs.

**Comment by ivirshup** [comment]
@emdann I have reuploaded that notebook to a gist here so you can see it: https://gist.github.com/ivirshup/ff6a2a78eb2061d1c45d32ff8f115bc3

If you'd like, you can also just download the `obs` data frame in memory like this:

```python
import h5py
import fsspec
from anndata.experimental import read_elem
# or from anndata.io import read_elem for 0.11

fs = fsspec.filesystem('s3', anon=True)

with h5py.File(
    fs.open("cellxgene-census-public-us-west-2/cell-census/2024-07-01/h5ads/0041b9c3-6a49-4bf7-8514-9bc7190067a7.h5ad")
) as f:
    obs = read_elem(f["obs"])
```

However this may be slower in practice, since it's many small requests in serial vs one big request.

**Comment by brianraymor** [comment]
Closing this issue. Added [Curators and Data Consumers want Discover API to return AnnData elements from a dataset](https://github.com/chanzuckerberg/single-cell-data-portal/issues/7402) to the 2025 backlog.

**Comment by giovp** [comment]
just came here to say that I needed the same thing and @ivirshup kindly pointed me to this issue, so +1 for this feature
