### ISSUE TITLE
chore: remove requirement for AWS_PROFILE

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/cellxgene-census#163]
Currently, one needs to have AWS_PROFILE set as an enviroment variable to be able to access cell census. I think your average comp bio will have limited experience with AWS profiles and such. I'm not sure why it's necessary to require any credentials whatsoever. Can this requirement be removed?

[Context](https://czi-sci.slack.com/archives/C048BN7K6U8/p1675207665755409)

[Pablo edit]
This only affects internal CZI users

## Definition of Done

Document best practices for internal users to avoid this issue as there are workarounds

**Comment by bkmartinjr** [comment]
even if this can't be fixed, it can be documented in a getting started guide, and perhaps in a better error message when the problem occurs....

**Comment by mlin** [comment]
https://github.com/boto/boto3/issues/1200

^ I think that's roughly what we need to do to access a public bucket without anything wanting any kind of credentials (but I think all our S3 I/O is going through TileDB and we'll have to look into how/whether that can configuration be fed through)

Internally in CZI each of us always needs to set `AWS_PROFILE` because of our multi-account architecture and [aws-oidc](https://github.com/chanzuckerberg/aws-oidc). Most AWS CLI users don't have that requirement (and if they do, then good chance they're already accustomed to it). But certainly we should test the UX in a fresh environment where AWS CLI hasn't yet been configured in any way.

**Comment by bkmartinjr** [comment]
Tip from @ebezzi -- use no-sign-request:
> s3 = boto3.client('s3', config=Config(signature_version=UNSIGNED))
Which is the same info Mike provided above.

**Comment by bkmartinjr** [comment]
Please fix this in `open_soma()` so that any API-based use of the census benefits from the fix.

**Comment by Bento007** [comment]
> But certainly we should test the UX in a fresh environment where AWS CLI hasn't yet been configured in any way.

The github action unit-tests does not have AWS_PROFILE set. So we can be confident public access works.

**Comment by pablo-gar** [comment]
Dup of #278
