### ISSUE TITLE
R API 1.0 is released to CRAN or RUniverse

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#192]
The minimal requirement for this issue to deposit the release in RUniverse. 

Please try to deposit in CRAN, if a blocker (work than requires more than 1 day) is encountered, then drop the CRAN deposition and create a new issue to track that.

**Comment by mlin** [comment]
@pablo-gar @ebezzi Would either of you be able to look into how to set up a suitable CZI/cellxgene "organization" on r-universe.dev, analogous to https://tiledb-inc.r-universe.dev/ ? what should it be named, who should own it, what logo to use, does central infra need to be in the loop, etc.

(I can experiment in the meantime in a personal area)

**Comment by pablo-gar** [comment]
@mlin see #359

**Comment by mlin** [comment]
We can consider this P1 not P0, because our package doesn't have any native-code extensions, installing the R package directly from github is *okay*...

https://github.com/chanzuckerberg/cellxgene-census/blob/13c4b1d04f0bb36ea5c73015972d29c96bf643b0/api/r/cellxgene.census/README.md?plain=1#L20

It'd still be much better to publish on r-universe, so let's keep pushing that, but if this ends up being the *last* thing otherwise blocking our 1.0 release, then we can compromise on it.
