### ISSUE TITLE
Add pre-calculated row-based (cell/obs) calculations to schema 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#289]
Originally contributed by Tim Trichie

## Description

To add these pre-calculated numbers to `census["census_data"][organism].obs`

1. count sum from `X["raw"]` - suggested `obs` column name `raw_sum`
2. number of nnz values  -  suggested `obs` column name `nnz`
~3. number of mithocondrial genes with non-zero values.~ Removed due to biological inaccuracy across datasets.
4. count average of nnz values -  suggested `obs` column name `raw_mean`
5. count variance of nnz values -  suggested `obs` column name `raw_variance`
6. number "measured" genes (sum of presence matrix) - suggested `obs` column name `n_measured_vars`

To add these pre-calculated numbers to `census["census_data"][organism].ms["RNA"].var`

1. number of nnz values  - suggested `var` column name `nnz`
2. number "measured" cells (sum of presence matrix) - suggested `var` column name `n_measured_obs`

## Context

These numbers are used for a variety of downstream operations, and having readily available can speed up the analysis of Cell Census data.

Specifically: 

- The count sum (1) is used for normalization, see details below from Tim Triche comments
- The number of mithocondrial genes (2) can be used as QC metric to assess the likelihood of a cell undergoing apoptosis.

## Relevance

It speeds up the process of analysis but it is not a blocker at the moment as these can be calculated downstream of the Cell Census.

See details below from Tim Triche

## Ideal behavior 

The pre-calculated numbers are included in the Cell Census natively 

## Schema addition

Under header "Feature metadata – `census_obj["census_data"][organism].ms["RNA"].var` – `SOMADataFrame`"

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>nnz</td>
    <td>int64</td>
    <td>For this feature, the number of non-zero values present in the `X['raw']` counts (raw) matrix.</td>
  </tr>
  <tr>
    <td>n_measured_obs</td>
    <td>int64</td>
    <td>For this feature, the number of observations present in the source H5AD (sum of feature presence matrix).</td>
  </tr>
</tbody>
</table>

Under header "Cell metadata – `census_obj["census_data"][organism].obs` – `SOMADataFrame`"

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
<tr>
    <td>nnz</td>
    <td>int64</td>
    <td>For this observation, the number of non-zero measurements in the `X['raw']` counts (raw) matrix.</td>
  </tr>
  <tr>
    <td>n_measured_vars</td>
    <td>int64</td>
    <td>For this observation, the number of features present in the source H5AD (sum of feature presence matrix).</td>
  </tr>
  <tr>
    <td>raw_sum</td>
    <td>float32</td>
    <td>For this observation, the sum of the count (raw) matrix values.</td>
  </tr>
  <tr>
    <td>raw_mean</td>
    <td>float32</td>
    <td>For this observation, the mean of the count (raw) matrix values./td>
  </tr>
  <tr>
    <td>raw_variance</td>
    <td>float32</td>
    <td>For this observation, the variance of the counts (raw) matrix values.</td>
  </tr>
</tbody>
</table>

### Version X.X.X

- Adds `nnz` and `n_measured_obs` columns to `ms["RNA"].var` dataframe.
- Add `nnz`, `n_measured_vars`, `raw_sum`, `raw_mean` and `raw_variance` columns to `obs` dataframe.

**Comment by pablo-gar** [comment]
This needs input from Tim Trichie who is the original requestor. I have asked him to contribute to this thread.

@brianraymor tagging you for visibility since I believe this would one area to push down to the dataset schema if were to purse it.

**Comment by ttriche** [comment]
scanpy and similar packages typically express normalized counts as the fraction of a hypothetical 20,000 or so fragments per cell. The option to exclude highly-expressed genes which can otherwise distort inference (e.g. immune-stimulated genes, interferons, etc.) was highlighted in [Weinreb 2018](https://www.pnas.org/doi/10.1073/pnas.1714723115) but at the end of the day, most analyses simply use `(counts[cell, gene] / sum(counts[cell, ])) * target_fragments`.  If `target_fragments` == `1e6` then the above is counts-per-million or CPM, and if we take `log(1 + CPM)` then the mean is decoupled from the variance and we can run around fitting linear models and such without being bitten too badly. 

The thing that slows down the above calculations (especially when focusing on one or a few genes) is that we'd like to have `sum(counts[cell,])` pre-computed and just divide each gene's counts through by (that number divided by `target_fragments`, which again is typically 1 million fragments per RNAseq library, from back in the bulk days). 

I wonder if the row sums (total unique fragment counts for a given cell) are, somewhere, stored for QC purposes? That could just be repurposed (or imported) and everyone could proceed on their merry way.  This is super helpful when one wants to look at the relative abundance of a handful of genes without doing a full scan of the data. (The "right" way to do this is with molecular spike-ins for the libraries, but since very few groups do that, this is not terrible (see e.g. [Booeshaghi et al 2021](https://www.biorxiv.org/content/10.1101/2022.05.06.490859v1.full) among others; `log1p(c/p)` isn't bad, is much faster than alternatives like sctransform, and doesn't end up as a false positive generating machine).

**Comment by pablo-gar** [comment]
Thanks for the detailed context @ttriche.

>  if the row sums (total unique fragment counts for a given cell) are, somewhere, stored for QC purposes?

not at the moment.

Tagging @BAevermann  and @jahilton for visibility.

**Comment by jahilton** [comment]
One caveat here is that we are not getting the full gene set from any dataset. Some are the 30-35k genes that are in the CellRanger default references, some are the ~60k that are in the unfiltered GENCODE references, and some have filtered from one of those down to as low as ~20k genes (we try to dissuade submission of any less than that).
On top of that, any gene not present in the pinned annotation (currently GENCODE V38) is filtered out upon submission.

Does that variability change how these metrics should be presented? Or potentially lead to misinterpretation or confusion?
e.g. what if on dataset filtered out some/all of the mito genes?

**Comment by pablo-gar** [comment]
Per triage with SMEs this should be a Census-specific schema addition. In addition the following suggestions were made and the top-level comment has been updated accordingly.

- Doing sums and average per gene is dangerous. 
- We need to account or include info for the number of genes measured per cell in any associated calculations.
