### ISSUE TITLE
Add splicing information to Cell Census 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#291]
Original contributor Zach DeBruine @zdebruine 

## Description

To have splicing information/status in the Cell Census. Specifically, for a given gene (or transcript?) to be able to separate spliced counts vs unspliced counts

## Context

Splicing information is useful for modeling biological behavior and in particular [trajectory analysis](http://bioconductor.org/books/3.14/OSCA.advanced/trajectory-analysis.html), e.g. pseudotime 

## Relevance

It currently blocks certain analysis as the aforementioned trajectory analysis.

See also comment below by @zdebruine 

## Ideal behavior 

See comment below by @zdebruine

**Comment by pablo-gar** [comment]
Zach, can you please add any other information as comment for the Context, Relevance, an Ideal behavior sections?

**Comment by zdebruine** [comment]
Certainly! It would be great to include unspliced transcript expression alongside spliced transcript expression, as it can provide valuable information in single-cell sequencing assays. 

**Context and Relevance:**  Here are some reasons why unspliced transcript expression is important (and I'm not an expert per se on this):

- Unspliced transcript expression can be used to map cellular differentiation trajectories in real-time, rather than relying on pseudotime (as seen in scVelo/velocyto).
- Including unspliced transcript expression in dimension reduction analysis can provide better sensitivity and more powerful results, as it effectively doubles the amount of information available. I would be happy to provide an example of this in a post if desired.
- Excluding unspliced transcript expression means throwing away up to ~40% of the mapped sequencing reads (based on data I have analyzed from developing mouse embryos), which contains useful information.
- The ratio of unspliced to spliced transcript expression is a measure of cellular transcriptional activity, and can be used to distinguish between active and quiescent cells.
- The inclusion of unspliced transcript expression can support research that may be underpowered due to small sample sizes, as there are currently no large datasets available (to my knowledge) that provide both spliced and unspliced transcript count matrices.

**Ideal Behavior:**  Simply add rows to the matrix for unspliced features.  You may add feature metadata so that it is easy to filter just spliced, if desired, or simply append "_unspliced" to the feature name, however you like.

**Comment by pablo-gar** [comment]
Thanks @zdebruine this is great!

**Comment by brianraymor** [comment]
@pablo-gar to review with @BAevermann and Lattice.

**Comment by BAevermann** [comment]
I am confused, are we proposing: 
1. Adding support for differentially spliced transcripts
2. Adding support for Unspliced transcripts only, i.e., whole gene (including all introns)
Thanks!

**Comment by BAevermann** [comment]
Thanks for the clarification @zdebruine!
This may be a daft question, but how does the resulting expression matrices look different between "unspliced" counts to the current "gene" counts (CELLxGENE schema requires Ensemble gene IDs). I am just curious how we can determine if the gene concept used contains all introns/exons or omits portions. 

Thanks!

b.

**Comment by zdebruine** [comment]
@BAevermann I am not sure.  This may be more of a question for the authors of velocyto or scVelo who have more experience with various builds.  I have only used processed data from other authors and found it to significantly improve the power of dimension reduction, hence the request.

**Comment by BAevermann** [comment]
Thanks @zdebruine! I will look into velocyto and scVelo to get a better understanding about how they invoke annotation in their data workflow...

**Comment by pablo-gar** [comment]
@BAevermann This doesn't seem to be addressable at Census level and looks more of a general dataset schema and data strategy topic.

Is there a place where we track these type of issues that I can defer to you?

cc @brianraymor

**Comment by BAevermann** [comment]
I agree that its not applicable to the Census. We could move this ticket to single-cell-curation
