### ISSUE TITLE
Add `doi` to schema

### ISSUE THREAD

**Issue by lauraluebbert** [chanzuckerberg/cellxgene-census#444]
## Description

It would be great if "doi" could be added as a [metadata attribute](https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_schema.md#cell-metadata--census_objcensus_dataorganismobs--somadataframe) (similar to the existing "dataset_id").  

## Impact

It would be very useful to support fetching data by "doi" and/or adding the DOI as a column in the returned metadata. This would greatly simplify the exploration of data associated with a paper of interest and finding the relevant papers associated with data of interest.

## Ideal behavior 

1. Being able to fetch all data associated with a paper by DOI. 
3. Being able to add the DOI to a returned metadata object. 

## EDIT by @pablo-gar 

TODO:

- Update Census schema to add new column to `census['census_info']['datasets']`:  `doi`

## Schema addition

Under header **Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]` – `SOMADataFrame``**

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>doi</td>
    <td>string</td>
    <td rowspan="5">As defined in CELLxGENE Discover <a href="https://api.cellxgene.cziscience.com/curation/ui/">data schema</a> (see &quot;Schemas&quot; section for field definitions)".</td>
  </tr>
</tbody>
</table>

Under header **Changelog**

### Version X.X.X

- Adds `doi` to "Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]`"

**Comment by davemcg** [comment]
Related - you do provide the `dataset_id`. Example: `f7c1c579-2dc0-47e2-ba19-8165c5a0e353`

On the cellxgene explorer page *most of the time* you can load the data like so: `https://cellxgene.cziscience.com/e/f7c1c579-2dc0-47e2-ba19-8165c5a0e353.cxg/`

Is there another way to link the dataset_id to the doi or SRA deposit?

**Comment by pablo-gar** [comment]
This will become actionable once this is completed: https://github.com/chanzuckerberg/single-cell-curation/issues/412.

I have edited the top-level comment to reflect this

**Comment by brianraymor** [comment]
I would probably not use the API reference in the schema because it is an implementation detail (the source of the doi). I would document it is the curie reference for the publication DOI in a CELLxGENE Discover Collection. For example

` curie       :=   [ [ prefix ] ':' ] reference`

For example, the reference for doi:10.1016/j.cell.2021.01.053 curie is 10.1016/j.cell.2021.01.053 - eliminating the "doi" prefix and the ":" separator. 

Returning the DOI reference in responses, helps consumers of the metadata because no information needs to be stripped before the `DOI` can be passed to services such as crossref or semantic scholar:

```

https://api.crossref.org/works/10.1016/j.cell.2021.01.053

```

**Comment by pablo-gar** [comment]
This issue was broken into 2:

- DOI (this)
- Citation #559 

DOI is already included in the data frame `census_obj["census_info"]["dataset"]` with the key `publication_doi`, this information can joined to `obs` via `dataset_id` which is present in both data frames

Therefore this issue can be considered completed.
