### ISSUE TITLE
Count Data

### ISSUE THREAD

**Issue by Yanay1** [chanzuckerberg/cellxgene-census#465]
## Description

It would be very useful to add metadata describing the availability of raw count data and standardize how to access it for given h5ads better.

## Context

When using h5ads from the census, many have count data in the `.raw.X` slot, however, others have it in the original `.X` slot or don't have it all.

## Impact

There are countless normalization methods for single cell data and it's difficult to tell which were used for a given dataset. Providing raw count data allows us to run our own normalizations in a standardized way.

## Alternatives you've considered

There are some automatic scanpy checks that are possible but it is still wasteful to download a dataset that doesn't have raw data.

## Ideal behavior 

All h5ads should have raw count data available in a standardized slot, perhaps `.raw.X`, and you should be able to filter queries to the census for datasets that only have count data.

**Comment by davemcg** [comment]
All data in Census is *supposed* to have raw counts...

https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_schema.html#data-included-in-the-census

Can someone comment on whether this is being enforced?

**Comment by pablo-gar** [comment]
@davemcg 

Hi Dave, all data in the Census are raw counts. It is currently enforced as part of our build process of the Census.

I believe @Yanay1 is referring to the **source H5AD files** that are used to build the Census. These files can be downloaded with the api via:

`cellxgene_census.download_source_h5ad()` see reference doc [here](https://chanzuckerberg.github.io/cellxgene-census/python-api.html#open-retrieve-cell-census-data). 

@Yanay1 Since these files are part of the CELLxGENE ecosystem and they are RNA data then they are required to have raw counts (see the corresponding schema requirement [here](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#x-matrix-layers)). In addition, data contributors _may_ include normalized values. 

That leads to two scenarios:

1. An H5AD only has raw counts
2. An H5AD has both raw counts and normalized values. 

There's a simple heuristic you can follow to alway fetch the raw counts:

- If `adata.raw.X` exists then those are the raw counts.
- If `atada.raw.X` does NOT exist, then the raw counts are in `adata.X`

Please let me know if this resolves your question.

**Comment by davemcg** [comment]
Thanks - that is helpful. I couldn't find any discussion about data processing - are there any standards about how the quantification happens? Someone could be using CellRanger, or STAR, or kbtools, or alevin-fry. Then there are several different options for the genome/transcriptome models.....

**Comment by Yanay1** [comment]
That helps, thanks!
