### ISSUE TITLE
Handling of multi organism datasets

### ISSUE THREAD

**Issue by Yanay1** [chanzuckerberg/cellxgene-census#469]
## Description

There are a few datasets that have multiple organisms in them, and this may increase over time.

## Context

Here are two examples of datasets with multiple organisms in them: 

1: https://cellxgene.cziscience.com/collections/367d95c0-0eb0-4dae-8276-9407239421ee

2: https://cellxgene.cziscience.com/collections/0a77d4c0-d5d0-40f0-aa1a-5e1429bcbd7e

In the first example, the species are mixed together in the anndata and it is unclear how the gene subset was determined.

In the second example, the species are separate and downstream users can do any kind of multi-species integration they want using these anndatas, rather than having to find the raw, un-joined data. 

## Impact

Each anndata should have one species only. This would improve the ability to do multi-species analysis using the census. 

## Alternatives you've considered

When the species are joined and some kind of common name (or ortholog) gene subset is used, there is no way to reverse that. The only alternative is to go to the original paper's data source.

## Ideal behavior 

Each anndata should have one species only.

**Comment by pablo-gar** [comment]
Hi @Yanay1 

This relates to the [data schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md) we have for the source h5ads.

What you are seeing is a direct consequence of certain level of flexibility we have in the schema. We allow data contributors to submit datasets in any form that fits their publication needs so long as:

- The gene space they use is from human or mouse.

This has lead t the following cases:

- Datasets having cells from multiple organisms and utilizing a gene space for either mouse or human before the data makes it to CELLxGENE.
- Datasets having cells from one organism and utilizing a gene space for either mouse or human.

We try to stay away from datasets for which the gene space and the cells are from different species, and therefore we discourage submission of multi-species dataset. But since we don't enforce this we do have a few of these cases.

I'm tagging @brianraymor since he is the owner of our source h5ad schema @brianraymor.


------

**Please note that Census data (not the source h5ads) does enforce that only cells that have a matching species in their genes are included, so your issue does not extend to the Census data itself.**

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-curation #450](https://github.com/chanzuckerberg/single-cell-curation/issues/450) via [**Zenhub**](https://www.zenhub.com/)
