### ISSUE TITLE
[r] Improve R GHA build time

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#507]
## Motivation

Impacts development iteration speed.

## Definition of Done

Ideally:
The [R GHA workflow](https://github.com/chanzuckerberg/cellxgene-census/actions/workflows/r-check.yml) runs in < 10m. 

Minimally:
Only run this workflow when R API source code or R-related GHA workflows change.

## Tasks

- [ ] Investigate cause
- [ ] Optimize

**Comment by mlin** [comment]
Maybe duplicating #309 

Lowest-hanging fruit --> https://github.com/chanzuckerberg/cellxgene-census/blob/e708d54dd26348e27d426bc890c13805097462d8/.github/workflows/r-check.yml#L24-L27

Right now all dependencies are built from source on every build. The dependencies action has an automatic caching functionality which we disable because of how we're currently tracking the bleeding-edge tiledbsoma r-universe build. I think an easy win may be to turn on the caching (by deleting above lines), then add a step afterwards that installs an up-to-date tiledbsoma. That way all other dependencies will be satisfied from the automatic cache.

**Comment by atolopko-czi** [comment]
Definitely a dup, ty! Closing. Feel free to move over your last comment to #309, @mlin, if you think it's useful there too.
