### ISSUE TITLE
Add search functionality to cellxgene-census docs

### ISSUE THREAD

**Issue by ayushnoori** [chanzuckerberg/cellxgene-census#620]
## Description

Add search functionality to `cellxgene-census` documentation website at https://chanzuckerberg.github.io/cellxgene-census/index.html.

## Context

See https://cziscience.slack.com/archives/C04LMG88VKJ/p1689261048038369.

**Comment by ivirshup** [comment]
Some updates after an initial investigation:

* Sphinx by default includes search entirely client side search. E.g. you start a new project and run `make html`, there will be a functioning search bar
* Currently this feature is disabled in the census docs. The search index is still built, but the search bar isn't excluded by using a blank `"searchbox.html"` template. If I remove that, a search bar is visible but still seems non-functional due to a missing jquery. Still not sure how that is being excluded or how I can get it back.

**Comment by ivirshup** [comment]
As an alternative to client side search, there is also Algolia DocSearch. I've had a little bit of trouble with it in the past, but think it's overall fine. No idea if it's going to give users cookies.

**Comment by ivirshup** [comment]
Closing, since it was fixed in #1166

**Comment by ayushnoori** [comment]
Great, thanks so much, @ivirshup!
