### ISSUE TITLE
[python] The normalized layer must never codify a zero for an associated value of 1 in the raw layer

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#706]
## Describe the bug

Certain values in the normalized layer are 0 and their corresponding raw counts are 1. This should never happen as one of the immediate transformations for the normalized layer are to perform the log, and the log of 0 is -Inf.

## To Reproduce

```python
import cellxgene_census
import tiledbsoma

census = cellxgene_census.open_soma(census_version = "latest")

#Tabula Muris Senis aorta data
dataset_id = "0380ddce-c31b-422a-88fe-34a1945bd949"
organism = "mus_musculus"
cell_filter = f"dataset_id == '{dataset_id}'"

mus_musculus = census["census_data"][organism]

query = mus_musculus.axis_query(
  measurement_name = "RNA",
  obs_query = tiledbsoma.AxisQuery(value_filter = cell_filter)  
)

raw = query.X("raw").tables()
nor = query.X("normalized").tables()

raw_chunk = next(raw).to_pandas()  
nor_chunk = next(nor).to_pandas()  

raw_chunk.loc[raw_chunk.soma_data == 1,]
#          soma_dim_0  soma_dim_1  soma_data
# 11          3587191         114        1.0
# 31          3587191         265        1.0
# 35          3587191         320        1.0
# 38          3587191         336        1.0
# 55          3587191         425        1.0
# ...             ...         ...        ...
# 1900076     3588096       30458        1.0
# 1900079     3588096       30495        1.0
# 1900080     3588096       30509        1.0
# 1900084     3588096       32012        1.0
# 1900086     3588096       32078        1.0
# 
# [178902 rows x 3 columns]


nor_chunk.loc[raw_chunk.soma_data == 1,]
#          soma_dim_0  soma_dim_1  soma_data
# 11          3587191         114   0.000000
# 31          3587191         265   0.000000
# 35          3587191         320   0.000000
# 38          3587191         336   0.000000
# 55          3587191         425   0.000000
# ...             ...         ...        ...
# 1900076     3588096       30458   0.000019
# 1900079     3588096       30495   0.000019
# 1900080     3588096       30509   0.000019
# 1900084     3588096       32012   0.000019
# 1900086     3588096       32078   0.000019

query.close()
census.close()
```

## Expected behavior

The normalized layer should have a >0 lower bound for all equivalent raw nnz's

**Comment by bkmartinjr** [comment]
This is as designed, and is due to two factors:
* A raw count value that is very small compared to the sum of the raw counts for a given obs/row, resulting in a normalized (fractional) value that is very small.
* Storing the normalized layer with a reduction in precision (i.e. we do not save the entire 32 bits of data).  Recall that precision reduction is currently defined as saving roughly the first 18 bits of precision (roughly 5.4 decimal digits).

All values in the normalized matrix are intended to be "close to" their stored value.  The precision reduction is implemented as `round((raw_float - offset) / factor)` on write (reverse that on read), and our current schema defines `factor=1./*2**18` and `offset=0.5`

Example above - for soma_dim_0 == 3587191:
```
In [1]: raw_df[raw_df.soma_dim_0 == 3587191].soma_data.sum()
Out[1]: 1932967.0

In [2]: raw_df[(raw_df.soma_dim_0 == 3587191) & (raw_df.soma_dim_1 == 50002)]
Out[2]: 
         soma_dim_0  soma_dim_1  soma_data
1896585     3587191       50002        1.0

In [3]: value = 1.0/1932967.0

In [4]: value
Out[4]: 5.173394062081764e-07

In [5]: offset = 0.5

In [6]: factor = 1.0 / 2**18

In [7]: factor * round((value-offset)/factor) + offset
Out[7]: 0
```

The alternative to not using precision reduction is an increase in the normalized layer data size (the conversion to fractions increases the apparent - not actual - information content of the layer, which the Zstd compression is not able to recover).

We could increase the significant digits saved, but this problem will still occur in the limit (_even if we save all 32 bits_).  It just becomes far less likely as precision is increased (e.g., roughly 20 bits would have captured this example as a non-zero).

Alternatively, could write a minimum value into each location with counts below the precision reduction floor. That will have the side effect of causing the sum of the normalized row to further diverge from 1.0.  The minimum value written would roughly be `(offset+sigma)*factor`, where sigma is a very small (but non-zero) float value.

We could also use a combination of the two, which might balance these competing issues.
