### ISSUE TITLE
get_anndata : memory leak (?) when filter leads to an empty data

### ISSUE THREAD

**Issue by AlixSil** [chanzuckerberg/cellxgene-census#807]
The function get_anndata seems to be leaking memory (or at least is using more and more memory without end) when obs_value_filter ask for an empty anndata

Example: 
```python
start_time = time.time()
with cellxgene_census.open_soma() as census:
    adata = cellxgene_census.get_anndata(
        census,
        "Homo Sapiens",
        obs_value_filter=f"dataset_id == 'cizuebgeuirgfkergneirng'",
    )
end_time = time.time()
print(f'time elapsed {end_time-start_time}')
``` 
Ran for more than 3 minute and consummed 40G of RAM before being manually interupted.

I reproduced the bug on a Google Cloud VM and a local MAC. Bug Is also present when connecting to a different SOMA database.

I'm using cellxgene-census 1.6.0

**Comment by bkmartinjr** [comment]
Thank you for the bug report @AlixSil

This is likely caused by single-cell-data/TileDB-SOMA#1703, which is fixed but not yet released.  I have verified that your test case works as expected using the head of tiledbsoma main.

We do not have a firm release date for the fix, but I estimate that it will occur in the next 2-4 weeks.

**Comment by AlixSil** [comment]
Thanks for your quick answer !
