### ISSUE TITLE
Reduce resources needed for running comp_bio* notebooks

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#85]
The following notebooks require either too much memory and/or time to run. They should be modified to run in a machine with about 32GB of memory and should take less than 15 min to run each. (these numbers serve for guidance)

@atolopko-czi:
- [x] Benchmark runtime of all notebooks and revise below list, as needed. 

@pablo-gar Revise notebooks as needed:
- [ ] [comp_bio_data_integration_scvi.ipynb](https://github.com/chanzuckerberg/cell-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_data_integration_scvi.ipynb)
- [x] [comp_bio_explore_and_load_lung_data.ipynb](https://github.com/chanzuckerberg/cell-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_explore_and_load_lung_data.ipynb)
- [x] [census_compute_over_X.ipynb](https://github.com/chanzuckerberg/cell-census/blob/main/api/python/notebooks/api_demo/census_compute_over_X.ipynb)
- [x] comp_bio_normalizing_full_gene_sequencing.ipynb

**Comment by atolopko-czi** [comment]
[notebooks-runtime-summary.txt](https://github.com/chanzuckerberg/cell-census/files/10494106/notebooks-runtime-summary.txt)

See `elapsed` (in MM:SS.SSS) and `maxresident` (in kb) to see which notebooks are candidates for improvements.

* `analysis_demo/comp_bio_explore_and_load_lung_data.ipynb` failed outright on a 64GB instance
* `analysis_demo/comp_bio_normalizing_full_gene_sequencing.ipynb` failed due to an apparent data-related issue (error in attached file)


Command to run & time all notebooks:
```
ls api_demo/census_high_variable_genes.ipynb | xargs -n 1 time jupyter-nbconvert --to notebook --execute 2>&1 | tee -a notebook-timings.txt
```

**Comment by pablo-gar** [comment]
Addressed in #101 #98 #92 #91

**Comment by pablo-gar** [comment]
Re opened because of #112

**Comment by brianraymor** [comment]
Closed as complete per triage.
